import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@/styles/main.scss";
import Header from "@/components/Header";
import StyledComponentsRegistry from "@/lib/registry";
import { CalendarProvider } from "@/context/CalendarContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <StyledComponentsRegistry>
          <CalendarProvider>
            <div
              style={{
                display: "flex",
                height: "100vh",
                overflow: "hidden",
                flexDirection: "column",
                width: "100vw",
              }}
            >
              <div
                style={{
                  display: "flex",
                  backgroundColor: "var(--color-toolbar-bg)",
                  width: "100%",
                  height: "auto",
                }}
              >
                {/* <Square /> */}
                <Header />
              </div>
              <div
                style={{
                  display: "flex",
                  overflow: "hidden",
                  justifyContent: "center",
                  alignItems: "center",
                  width: "100%",
                  height: "100%",
                }}
              >
                {/* <Sidebar /> */}
                {children}
              </div>
            </div>
          </CalendarProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
