import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@/styles/custom-calendar.scss";
import Sidebar from "@/components/Sidebar";
import Header from "@/components/Header";
import StyledComponentsRegistry from "@/lib/registry";
import Square from "@/components/Square";
import { CalendarProvider } from "@/context/CalendarContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <StyledComponentsRegistry>
          <CalendarProvider>
            <div
              style={{
                display: "flex",
                width: "100vw",
                height: "auto",
                padding: "3px 10px",
                overflow: "hidden",
              }}
            >
              <div
                style={{
                  display: "flex",
                  width: "180px",
                  height: "auto",
                  padding: "3px 10px",
                  flexDirection: "column",
                }}
              >
                <Square />
                <Sidebar />
              </div>
              <div
                style={{
                  display: "flex",
                  flexDirection: "column",
                  margin: "3px 10px",
                  flexGrow: 1,
                  overflow: "hidden",
                }}
              >
                <Header />
                {children}
              </div>
            </div>
          </CalendarProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
